### ISSUE TITLE
Host validation missing

### ISSUE THREAD

**Issue by morrah** [cTapuk/alipic#1]
Without host validation in [loader.php#L19](https://github.com/cTapuk/alipic/blob/master/loader.php#L19) server traffic could be exhausted requesting large or limitless files.

**Comment by cTapuk** [comment]
Yeah you are right.

**Comment by cTapuk** [comment]
Fixed. thx.

**Comment by morrah** [comment]
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.1.0-amd64-netinst.iso?aliexpress.com still works

**Comment by cTapuk** [comment]
Lol. Smart move. Any idea how to close it properly?

**Comment by morrah** [comment]
regular expression https://regex101.com/r/cwP60p/2
or php function [parse_url()](http://php.net/manual/en/function.parse-url.php)

**Comment by cTapuk** [comment]
Done with regex. Modify it for hz.ru.aliexpress.com Check it [loader.php#L15](https://github.com/cTapuk/alipic/blob/master/loader.php#L15)

**Comment by morrah** [comment]
Your regex could be bypassed with a custom subdomain: https://aliexpress.com.mysite.ru/largefile.tmp

**Comment by cTapuk** [comment]
Ok. Need both. Regex and parse_url

**Comment by cTapuk** [comment]
Apply both parse_url and regex for it. [here](https://github.com/cTapuk/alipic/blob/master/loader.php#L16)
Are u a tester dude morrah?

**Comment by morrah** [comment]
may be it's enough to add a slash at the end of your regexp, so "aliexpress.com" couldn't be used as a subdomain name: `/^https?:\/\/(\w+\.)*aliexpress\.com\//`

**Comment by morrah** [comment]
yea, your solution should work too, i think

**Comment by cTapuk** [comment]
Many thanks for help.
